version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./infrastructure/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongu
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodb
      - seaweedfs-master
      - seaweedfs-volume
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongu:mongo@mongodb:27017/
      - JWT_SECRET=secret

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes:
  mongodb:
