version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./infrastructure/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongu
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodb
      - seaweedfs-master
      - seaweedfs-volume
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongu:mongo@mongodb:27017/
      - JWT_SECRET=secret

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    command: "master -ip=seaweedfs-master -defaultReplication=001"
    ports:
      - "9333:9333" # Master API
      - "19333:19333" # Internal communication
    networks:
      - app_network

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    command: "volume -mserver=seaweedfs-master:9333 -port=8080 -publicUrl=seaweedfs-volume:8080"
    depends_on:
      - seaweedfs-master
    volumes:
      - seaweedfs_data:/data
    ports:
      - "8080:8080" # Volume API
      - "18080:18080" # Admin UI
    networks:
      - app_network

volumes:
  seaweedfs_data:

networks:
  app_network:
    driver: bridge
