name: frontend-test

on:
  pull_request:
    paths:
      - ".github/**"
      - ".frontend/**"

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: build
        run: npm run build
        working-directory: ./frontend
